[project]
type = "Text"
help = "Name of project"

[build]
type = "Select"
help = "Build system"
choices = [
  "nix",
  "guix"
]

[targets]
type = "MultiSelect"
help = "Compilation targets"
choices = [
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
]
